"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import NavbarComponent from "./components/NavbarComponent";
import { Code } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="dark text-foreground bg-background">
            <NavbarComponent />
            {children}
            <Code className="mx-auto mt-10 py-10 text-center w-full" size="md">
              Made with ❤️ by Sahil Saha
            </Code>
          </main>
        </Providers>
      </body>
    </html>
  );
}
